# coding: utf-8
from __future__ import absolute_import


TBL_COMMENT_COL_IS_ADMIN_V_NO = 0
TBL_COMMENT_COL_IS_ADMIN_V_YES = 1

TBL_COMMENT_COL_IS_VIEWED_V_NO = 0
TBL_COMMENT_COL_IS_VIEWED_V_YES = 1

TBL_COMMENT_COL_IS_BLOCKED_V_NO = 0
TBL_COMMENT_COL_IS_BLOCKED_V_YES = 1
